sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project	practise-james
  - gcloud config set compute/zone asia-southeast1-a	
  - gcloud container clusters get-credentials multi-clusters
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t simplygwee/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true simplygwee/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
