apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: growthpersons-com-tls
spec:
  secretName: growthpersons-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: growthpersons.com
  dnsNames:
    - growthpersons.com
    - www.growthpersons.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - growthpersons.com
          - www.growthpersons.com